.PHONY:	init,clean
build:
	mvn package
init:
	mvn archetype:generate
#mvn -B archetype:generate -DgroupId=com.zztest  -DartifactId=zztest -DarchetypeArtifactId=maven-archetype-quickstart
clean:
	rm -rf *.class
